//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub mod prelude;

pub mod approvals;
pub mod episode_speakers;
pub mod episodes;
pub mod parts;
pub mod sections;
pub mod speakers;
pub mod users;
pub mod words;
