//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "parts")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub episode_id: i32,
    pub episode_speaker_id: i32,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    #[sea_orm(column_type = "Double")]
    pub starts_at: f64,
    #[sea_orm(column_type = "Double")]
    pub ends_at: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::episode_speakers::Entity",
        from = "Column::EpisodeSpeakerId",
        to = "super::episode_speakers::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    EpisodeSpeakers,
    #[sea_orm(
        belongs_to = "super::episodes::Entity",
        from = "Column::EpisodeId",
        to = "super::episodes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Episodes,
    #[sea_orm(has_many = "super::sections::Entity")]
    Sections,
}

impl Related<super::episode_speakers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EpisodeSpeakers.def()
    }
}

impl Related<super::episodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Episodes.def()
    }
}

impl Related<super::sections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sections.def()
    }
}
