//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::approvals::Entity as Approvals;
pub use super::episode_speakers::Entity as EpisodeSpeakers;
pub use super::episodes::Entity as Episodes;
pub use super::parts::Entity as Parts;
pub use super::sections::Entity as Sections;
pub use super::speakers::Entity as Speakers;
pub use super::tokens::Entity as Tokens;
pub use super::users::Entity as Users;
