//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "words")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub section_id: i32,
    pub text: String,
    #[sea_orm(column_type = "Double")]
    pub starts_at: f64,
    #[sea_orm(column_type = "Double")]
    pub ends_at: f64,
    #[sea_orm(column_type = "Double")]
    pub probability: f64,
    pub hidden: bool,
    pub manual: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sections::Entity",
        from = "Column::SectionId",
        to = "super::sections::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Sections,
}

impl Related<super::sections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sections.def()
    }
}
